### ISSUE TITLE
Build fails : Cannot find module 'webpack/package.json'

### ISSUE THREAD

**Issue by LoicUV** [marcobiedermann/gatsby-plugin-svg-sprite#9]
The build fails with version `2.0.1`. Points to a line in `svg-sprite-loader` that was recently changed. Opened [an issue](https://github.com/kisenka/svg-sprite-loader/issues/338#issuecomment-509302539) on the repo explaining it. It does work with `svg-sprite-loader@4.1.3` for those that want to use it until they fix this error.

**Comment by rphansen91** [comment]
@LoicUV How did you get it to work with `svg-sprite-loader@4.1.3` that version is still using the `getWebpackVersion` method

**Comment by LoicUV** [comment]
@rphansen91 `getWebpackVersion` is a util function of `svg-sprite-loader`, the issue is with how the package.json file is imported. Here you can see the change between the working [4.1.3](https://github.com/kisenka/svg-sprite-loader/blob/48b19217d12cad555ed50ff63b19dd9bdc4bc633/lib/utils/get-webpack-version.js#L2) and [4.1.4](https://github.com/kisenka/svg-sprite-loader/blob/v4.1.4/lib/utils/get-webpack-version.js#L2)

**Comment by obetomuniz** [comment]
Updates?
